src/Entity/Action.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ActionRepository")
 * @Gedmo\SoftDeleteable(fieldName="deleted_at", timeAware=false, hardDelete=true)
 * @ExclusionPolicy("all")
 */
class Action {

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Expose
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Expose
     */
    private $actionType;

    /**
     * 
     * @ORM\Column(type="float", nullable=true)
     *  @Expose
     */
    private $amount;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Expose
     */
    private $date;

    /**
     * @ORM\Column(type="datetime")
     * @Expose
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Expose
     */
    private $last_updated_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Expose
     */
    private $deleted_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\pig", inversedBy="actions")
     *  @Expose
     * 
     */
    private $pig;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\house", inversedBy="actions")
     * 
     */
    private $house;
    private $colorClass;
    
    public  const ADD_TYPE="ADD";
    public  const SUBSTRACT_TYPE="SUBSTRACT";

    public function getColorClass(): ?string {
        $result = "red";
        if ($this->actionType === "ADD") {

            $result = "green";
        }
        $this->colorClass = $result;
        return $result;
    }

    public function setColorClass(): ?string {
        return $this->actionType;
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getActionType(): ?string {
        return $this->actionType;
    }

    public function setActionType(?string $actionType): self {
        $this->actionType = $actionType;

        return $this;
    }

    public function getAmount(): ?float {
        return $this->amount;
    }

    public function setAmount(?float $amount): self {
        $this->amount = $amount;

        return $this;
    }

    public function getDate(): ?DateTimeInterface {
        return $this->date;
    }

    public function setDate(?DateTimeInterface $date): self {
        $this->date = $date;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeInterface $created_at): self {
        $this->created_at = $created_at;

        return $this;
    }

    public function getLastUpdatedAt(): ?DateTimeInterface {
        return $this->last_updated_at;
    }

    public function setLastUpdatedAt(DateTimeInterface $last_updated_at): self {
        $this->last_updated_at = $last_updated_at;

        return $this;
    }

    public function getDeletedAt(): ?DateTimeInterface {
        return $this->deleted_at;
    }

    public function setDeletedAt(DateTimeInterface $deleted_at): self {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    public function getPig(): ?pig {
        return $this->pig;
    }
    public function getPigId(): ?int {
        return $this->pig->getId();
    }
    public function getHouseId(): ?int {
        return $this->house->getId();
    }


    public function setPig(?pig $pig): self {
        $this->pig = $pig;

        return $this;
    }

    public function getHouse(): ?house {
        return $this->house;
    }

    public function setHouse(?house $house): self {
        $this->house = $house;

        return $this;
    }
   
}

src/Form/ActionType.php
<?php

namespace App\Form;

use App\Entity\Action;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('actionType')
            ->add('amount')
            ->add('date')
            ->add('created_at')
            ->add('last_updated_at')
            ->add('deleted_at')
            ->add('pig_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Action::class,
        ]);
    }
}

src/Controller/ActionController.php
<?php

namespace App\Controller;

use App\Entity\Action;
use App\Entity\House;
use App\Form\ActionType;
use App\Repository\ActionRepository;
use App\Service\HouseService;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/action")
 */
class ActionController extends AbstractController {

    /**
     * @Route("/substract", name="substract", methods="GET")
     */
    public function substract(HouseService $houseService, Request $request) {

        $pig = $this->get('security.token_storage')->getToken()->getUser();

        $houseService->init($pig);
        $amount = $request->get("amount");
        $houseService->substractAmount($amount);
        $action = $houseService->getActionEntity();
        $jsonContent = $houseService->getActionJsonFormat($action);

        $response = new JsonResponse();
        $response->setData(array('amount_saved' => true, 'action_entity' => $jsonContent));

        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }

    /**
     * @Route("/add", name="add", methods="GET")
     */
    public function add(HouseService $houseService, Request $request) {


        $pig = $this->get('security.token_storage')->getToken()->getUser();
        $houseService->init($pig);
        $amount = $request->get("amount");
        $houseService->addAmount($amount);
        $action = $houseService->getActionEntity();

        $jsonContent = $houseService->getActionJsonFormat($action);

        $response = new JsonResponse();
        $response->setData(array('amount_saved' => true, 'action_entity' => $jsonContent));

        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }

    /**
     * @Route("/", name="action_index", methods="GET")
     */
    public function index(ActionRepository $actionRepository): Response {


        //$houseRepo = $this->getDoctrine()->getRepository(House::class);
        $pig = $this->get('security.token_storage')->getToken()->getUser();
        $joinedHouse = $pig->getJoinedHouse();
        //$house = $houseRepo->find($joinedHouse->getId());
        $filters = array(
            'house' => $joinedHouse->getId(),
        );

        $actions = $actionRepository->findBy($filters, array('created_at' => 'DESC'));

        return $this->render('action/action.html.twig', [
                    'actions' => $actions,
                    'house_id' => $joinedHouse->getId(),
                    'house' => $joinedHouse,
        ]);
    }

    /**
     * @Route("/new", name="action_new", methods="GET|POST")
     */
    public function new(Request $request): Response {
        $action = new Action();
        $form = $this->createForm(ActionType::class, $action);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($action);
            $em->flush();

            return $this->redirectToRoute('action_index');
        }

        return $this->render('action/new.html.twig', [
                    'action' => $action,
                    'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="action_show", methods="GET")
     */
    public function show(Action $action): Response {
        return $this->render('action/show.html.twig', ['action' => $action]);
    }

    /**
     * @Route("/{id}/edit", name="action_edit", methods="GET|POST")
     */
    public function edit(Request $request, Action $action): Response {
        $form = $this->createForm(ActionType::class, $action);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('action_edit', ['id' => $action->getId()]);
        }

        return $this->render('action/edit.html.twig', [
                    'action' => $action,
                    'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="action_delete", methods="DELETE")
     */
    public function delete(HouseService $houseService, Action $action): Response {


        $pig = $this->get('security.token_storage')->getToken()->getUser();

        $houseService->init($pig);
        $houseService->deleteAction($action);
        $response = new JsonResponse();
        $jsonContent = $houseService->getActionJsonFormat($action);

        $response->setData(array('amount_deleted' => true, 'action_entity' => $jsonContent));
        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }

}

templates/action/_delete_form.html.twig
<form method="post" action="{{ path('action_delete', {'id': action.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ action.id) }}">
    <button class="btn">Delete</button>
</form>

templates/action/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/action/action.html.twig
{% extends 'base.html.twig' %}

{% block title %}action{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('action-action') }}
{% endblock %}
{% block body %}

    <div id="php_data_to_js">
        <input id="house_id" value="{{house.id}}" hidden></input>

    </div>

    <div  class="offset-md-3 col-md-6 offset-xs-3 col-xs-6 col-xs">
        <div style="float:right" class="glyphicon glyphicon-cog"></div>
        <div style=" text-align:center">
            <div >

                <b>{{house.name}} amount</b> <div style="font-size:4em" readonly id="house_amount_value" value="">{{house.amount}}</div>

            </div>
            <div>
                <label  for="amount_to_commit">
                    Amount to commit</label>
                <div class="offset-md-2 col-md-8 form-group ">
                    <input style="text-align:center" id="amount_to_commit" class="form-control form-control-xlg input-lg" value="0"></input>
                </div>
                <div class="add-substract-buttons row  offset-md-2 col-md-8 offset-xs-2 col-xs-8 py-3">
                    <button id="add-amount-to-house-button" data-href="{{ path('add')}}"   type="button" class="col-md-6 form-control form-control-lg px-3 btn  button-green "><div id="new-amount-add-display"></div>ADD</button>
                    <button id="substract-amount-to-house-button" data-href="{{ path('substract')}}"  type="button" class=" col-md-6 form-control form-control-lg px-3 btn  button-red  "><div id="new-amount-substract-display"></div>SUBSTRACT</button>
                </div>
            </div>
        </div>

    </div>    
    <div class="p-5">

        <table class="table">
            <thead>
                <tr align="center">
                    <th>Pig</th>

                    <th>Amount</th>
                    <th>Date</th>

                    <th>actions</th>
                </tr>
            </thead>
            <tbody id="action-historic">
                {% for action in actions %}
                    <tr align="center">
                        <td >{{ action.pig.pseudoName }}</td>

                        <td class="{{ action.colorClass }}">{{ action.amount }}</td>
                        <td  >{{ action.date ? action.date|date('Y-m-d H:i:s') : '' }}</td>

                        <td class="actions-cell">
                            <!--a href="{{ path('action_show', {'id': action.id}) }}">show</a-->
                            <a title="edit" class="no-href-underline glyphicon glyphicon-pencil " href="{{ path('action_edit', {'id': action.id}) }}"></a>
                            <a  title="remove" class="remove-action no-href-underline glyphicon glyphicon-remove" data-href="{{ path('action_delete', {'id': action.id}) }}" ></a>
                        </td>


                    </tr>
                {% else %}
                    <tr>
                        <td colspan="8">no records found</td>
                    </tr>
                {% endfor %}


            </tbody>
        </table>
    </div>

    <div id="actions-cell-empty" hidden>
        <td >
            <a title="edit" class="no-href-underline glyphicon glyphicon-pencil " href="{{ path('action_edit', {'id': "tochange"}) }}"></a>
            <a title="remove" class="remove-action no-href-underline glyphicon glyphicon-remove" data-href="{{ path('action_delete', {'id': "tochange"}) }}"></a>
        </td>
    </div>

{% endblock %}

templates/action/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Action{% endblock %}

{% block body %}
    <div class="offset-md-3 col-md-6 col-xs">
    <h1>Edit Action</h1>

    {{ include('action/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('action_index',{houseId:action.houseId}) }}">back to list</a>

    {{ include('action/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/action/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Action index{% endblock %}

{% block body %}
    <h1>Action index</h1>
    
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>ActionType</th>
                <th>Amount</th>
                <th>Date</th>
                <th>Created_at</th>
                <th>Last_updated_at</th>
                <th>Deleted_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for action in actions %}
            <tr>
                <td>{{ action.id }}</td>
                <td>{{ action.actionType ? action.actionType|join(', ') : '' }}</td>
                <td>{{ action.amount }}</td>
                <td>{{ action.date ? action.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ action.createdAt ? action.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ action.lastUpdatedAt ? action.lastUpdatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ action.deletedAt ? action.deletedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('action_show', {'id': action.id}) }}">show</a>
                    <a href="{{ path('action_edit', {'id': action.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('action_new') }}">Create new</a>
{% endblock %}

templates/action/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Action{% endblock %}

{% block body %}
    <h1>Create new Action</h1>

    {{ include('action/_form.html.twig') }}

    <a href="{{ path('action_index') }}">back to list</a>
{% endblock %}

templates/action/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Action{% endblock %}

{% block body %}
    <h1>Action</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ action.id }}</td>
            </tr>
            <tr>
                <th>ActionType</th>
                <td>{{ action.actionType ? action.actionType|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Amount</th>
                <td>{{ action.amount }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ action.date ? action.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ action.createdAt ? action.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Last_updated_at</th>
                <td>{{ action.lastUpdatedAt ? action.lastUpdatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Deleted_at</th>
                <td>{{ action.deletedAt ? action.deletedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('action_index') }}">back to list</a>

    <a href="{{ path('action_edit', {'id': action.id}) }}">edit</a>

    {{ include('action/_delete_form.html.twig') }}
{% endblock %}